import type { SlashCommandCategory } from "@marcode/contracts";

export const BUILTIN_COMMAND_NAMES = new Set([
  "add-dir",
  "agents",
  "btw",
  "chrome",
  "clear",
  "color",
  "compact",
  "config",
  "context",
  "copy",
  "cost",
  "desktop",
  "diff",
  "doctor",
  "effort",
  "exit",
  "export",
  "extra-usage",
  "fast",
  "feedback",
  "branch",
  "help",
  "hooks",
  "ide",
  "init",
  "insights",
  "install-github-app",
  "install-slack-app",
  "keybindings",
  "login",
  "logout",
  "mcp",
  "memory",
  "mobile",
  "passes",
  "permissions",
  "plugin",
  "pr-comments",
  "privacy-settings",
  "release-notes",
  "reload-plugins",
  "remote-control",
  "remote-env",
  "rename",
  "resume",
  "review",
  "rewind",
  "sandbox",
  "schedule",
  "security-review",
  "skills",
  "stats",
  "status",
  "statusline",
  "stickers",
  "tasks",
  "terminal-setup",
  "theme",
  "upgrade",
  "usage",
  "vim",
  "voice",
]);

export const CLIENT_LOCAL_COMMANDS = new Set(["model", "plan", "default"]);

export function classifyCommand(name: string): SlashCommandCategory {
  if (CLIENT_LOCAL_COMMANDS.has(name)) return "client-local";
  if (BUILTIN_COMMAND_NAMES.has(name)) return "builtin";
  return "skill";
}
