import type { ThemeDefinition } from "../types";

export const AYU_THEMES: readonly ThemeDefinition[] = [
  {
    id: "ayu-light",
    label: "Ayu Light",
    group: "ayu",
    base: "light",
    variables: {
      "--background": "#fafafa",
      "--foreground": "#5c6166",
      "--card": "#f3f4f5",
      "--card-foreground": "#5c6166",
      "--popover": "#f3f4f5",
      "--popover-foreground": "#5c6166",
      "--primary": "#399ee6",
      "--primary-foreground": "#fafafa",
      "--secondary": "#e8eaed",
      "--secondary-foreground": "#5c6166",
      "--muted": "#e8eaed",
      "--muted-foreground": "#8a9199",
      "--accent": "#e8eaed",
      "--accent-foreground": "#5c6166",
      "--destructive": "#f51818",
      "--destructive-foreground": "#f51818",
      "--border": "#d8dae0",
      "--input": "#d8dae0",
      "--ring": "#399ee6",
      "--info": "#399ee6",
      "--info-foreground": "#399ee6",
      "--success": "#6cbf43",
      "--success-foreground": "#6cbf43",
      "--warning": "#f2ae49",
      "--warning-foreground": "#e6a031",
    },
  },
  {
    id: "ayu-mirage",
    label: "Ayu Mirage",
    group: "ayu",
    base: "dark",
    variables: {
      "--background": "#242936",
      "--foreground": "#cccac2",
      "--card": "#1f2430",
      "--card-foreground": "#cccac2",
      "--popover": "#1a1f2e",
      "--popover-foreground": "#cccac2",
      "--primary": "#73d0ff",
      "--primary-foreground": "#242936",
      "--secondary": "#33415e",
      "--secondary-foreground": "#cccac2",
      "--muted": "#33415e",
      "--muted-foreground": "#707a8c",
      "--accent": "#33415e",
      "--accent-foreground": "#cccac2",
      "--destructive": "#ff3333",
      "--destructive-foreground": "#ff3333",
      "--border": "#3d4455",
      "--input": "#3d4455",
      "--ring": "#73d0ff",
      "--info": "#73d0ff",
      "--info-foreground": "#73d0ff",
      "--success": "#bae67e",
      "--success-foreground": "#bae67e",
      "--warning": "#ffd580",
      "--warning-foreground": "#ffd580",
    },
  },
  {
    id: "ayu-dark",
    label: "Ayu Dark",
    group: "ayu",
    base: "dark",
    variables: {
      "--background": "#0b0e14",
      "--foreground": "#bfbdb6",
      "--card": "#0d1017",
      "--card-foreground": "#bfbdb6",
      "--popover": "#0d1017",
      "--popover-foreground": "#bfbdb6",
      "--primary": "#e6b450",
      "--primary-foreground": "#0b0e14",
      "--secondary": "#1c2030",
      "--secondary-foreground": "#bfbdb6",
      "--muted": "#1c2030",
      "--muted-foreground": "#565b66",
      "--accent": "#1c2030",
      "--accent-foreground": "#bfbdb6",
      "--destructive": "#d95757",
      "--destructive-foreground": "#d95757",
      "--border": "#252b38",
      "--input": "#252b38",
      "--ring": "#e6b450",
      "--info": "#39bae6",
      "--info-foreground": "#39bae6",
      "--success": "#7fd962",
      "--success-foreground": "#7fd962",
      "--warning": "#ffb454",
      "--warning-foreground": "#ffb454",
    },
  },
];
