import type { ThemeDefinition } from "../types";

export const CATPPUCCIN_THEMES: readonly ThemeDefinition[] = [
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    group: "catppuccin",
    base: "light",
    variables: {
      "--background": "#eff1f5",
      "--foreground": "#4c4f69",
      "--card": "#e6e9ef",
      "--card-foreground": "#4c4f69",
      "--popover": "#dce0e8",
      "--popover-foreground": "#4c4f69",
      "--primary": "#1e66f5",
      "--primary-foreground": "#eff1f5",
      "--secondary": "#ccd0da",
      "--secondary-foreground": "#4c4f69",
      "--muted": "#ccd0da",
      "--muted-foreground": "#6c6f85",
      "--accent": "#ccd0da",
      "--accent-foreground": "#4c4f69",
      "--destructive": "#d20f39",
      "--destructive-foreground": "#d20f39",
      "--border": "#bcc0cc",
      "--input": "#bcc0cc",
      "--ring": "#1e66f5",
      "--info": "#1e66f5",
      "--info-foreground": "#1e66f5",
      "--success": "#40a02b",
      "--success-foreground": "#40a02b",
      "--warning": "#df8e1d",
      "--warning-foreground": "#df8e1d",
    },
  },
  {
    id: "catppuccin-frappe",
    label: "Catppuccin Frapp\u00e9",
    group: "catppuccin",
    base: "dark",
    variables: {
      "--background": "#303446",
      "--foreground": "#c6d0f5",
      "--card": "#292c3c",
      "--card-foreground": "#c6d0f5",
      "--popover": "#232634",
      "--popover-foreground": "#c6d0f5",
      "--primary": "#8caaee",
      "--primary-foreground": "#303446",
      "--secondary": "#414559",
      "--secondary-foreground": "#c6d0f5",
      "--muted": "#414559",
      "--muted-foreground": "#a5adce",
      "--accent": "#414559",
      "--accent-foreground": "#c6d0f5",
      "--destructive": "#e78284",
      "--destructive-foreground": "#e78284",
      "--border": "#51576d",
      "--input": "#51576d",
      "--ring": "#8caaee",
      "--info": "#8caaee",
      "--info-foreground": "#8caaee",
      "--success": "#a6d189",
      "--success-foreground": "#a6d189",
      "--warning": "#e5c890",
      "--warning-foreground": "#e5c890",
    },
  },
  {
    id: "catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    group: "catppuccin",
    base: "dark",
    variables: {
      "--background": "#24273a",
      "--foreground": "#cad3f5",
      "--card": "#1e2030",
      "--card-foreground": "#cad3f5",
      "--popover": "#181926",
      "--popover-foreground": "#cad3f5",
      "--primary": "#8aadf4",
      "--primary-foreground": "#24273a",
      "--secondary": "#363a4f",
      "--secondary-foreground": "#cad3f5",
      "--muted": "#363a4f",
      "--muted-foreground": "#a5adcb",
      "--accent": "#363a4f",
      "--accent-foreground": "#cad3f5",
      "--destructive": "#ed8796",
      "--destructive-foreground": "#ed8796",
      "--border": "#494d64",
      "--input": "#494d64",
      "--ring": "#8aadf4",
      "--info": "#8aadf4",
      "--info-foreground": "#8aadf4",
      "--success": "#a6da95",
      "--success-foreground": "#a6da95",
      "--warning": "#eed49f",
      "--warning-foreground": "#eed49f",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    group: "catppuccin",
    base: "dark",
    variables: {
      "--background": "#1e1e2e",
      "--foreground": "#cdd6f4",
      "--card": "#181825",
      "--card-foreground": "#cdd6f4",
      "--popover": "#11111b",
      "--popover-foreground": "#cdd6f4",
      "--primary": "#89b4fa",
      "--primary-foreground": "#1e1e2e",
      "--secondary": "#313244",
      "--secondary-foreground": "#cdd6f4",
      "--muted": "#313244",
      "--muted-foreground": "#a6adc8",
      "--accent": "#313244",
      "--accent-foreground": "#cdd6f4",
      "--destructive": "#f38ba8",
      "--destructive-foreground": "#f38ba8",
      "--border": "#45475a",
      "--input": "#45475a",
      "--ring": "#89b4fa",
      "--info": "#89b4fa",
      "--info-foreground": "#89b4fa",
      "--success": "#a6e3a1",
      "--success-foreground": "#a6e3a1",
      "--warning": "#f9e2af",
      "--warning-foreground": "#f9e2af",
    },
  },
];
