import type { ThemeDefinition } from "../types";

export const GITHUB_THEMES: readonly ThemeDefinition[] = [
  {
    id: "github-light",
    label: "GitHub Light",
    group: "github",
    base: "light",
    variables: {
      "--background": "#ffffff",
      "--foreground": "#1f2328",
      "--card": "#f6f8fa",
      "--card-foreground": "#1f2328",
      "--popover": "#ffffff",
      "--popover-foreground": "#1f2328",
      "--primary": "#0969da",
      "--primary-foreground": "#ffffff",
      "--secondary": "#f6f8fa",
      "--secondary-foreground": "#1f2328",
      "--muted": "#f6f8fa",
      "--muted-foreground": "#656d76",
      "--accent": "#f6f8fa",
      "--accent-foreground": "#1f2328",
      "--destructive": "#cf222e",
      "--destructive-foreground": "#cf222e",
      "--border": "#d1d9e0",
      "--input": "#d1d9e0",
      "--ring": "#0969da",
      "--info": "#0969da",
      "--info-foreground": "#0969da",
      "--success": "#1a7f37",
      "--success-foreground": "#1a7f37",
      "--warning": "#9a6700",
      "--warning-foreground": "#9a6700",
    },
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    group: "github",
    base: "dark",
    variables: {
      "--background": "#0d1117",
      "--foreground": "#e6edf3",
      "--card": "#161b22",
      "--card-foreground": "#e6edf3",
      "--popover": "#1c2128",
      "--popover-foreground": "#e6edf3",
      "--primary": "#58a6ff",
      "--primary-foreground": "#0d1117",
      "--secondary": "#21262d",
      "--secondary-foreground": "#e6edf3",
      "--muted": "#21262d",
      "--muted-foreground": "#7d8590",
      "--accent": "#21262d",
      "--accent-foreground": "#e6edf3",
      "--destructive": "#f85149",
      "--destructive-foreground": "#f85149",
      "--border": "#30363d",
      "--input": "#30363d",
      "--ring": "#58a6ff",
      "--info": "#58a6ff",
      "--info-foreground": "#58a6ff",
      "--success": "#3fb950",
      "--success-foreground": "#3fb950",
      "--warning": "#d29922",
      "--warning-foreground": "#d29922",
    },
  },
];
