import type { ThemeDefinition } from "../types";

export const GRUVBOX_THEMES: readonly ThemeDefinition[] = [
  {
    id: "gruvbox-light",
    label: "Gruvbox Light",
    group: "gruvbox",
    base: "light",
    variables: {
      "--background": "#fbf1c7",
      "--foreground": "#3c3836",
      "--card": "#f2e5bc",
      "--card-foreground": "#3c3836",
      "--popover": "#ebdbb2",
      "--popover-foreground": "#3c3836",
      "--primary": "#458588",
      "--primary-foreground": "#fbf1c7",
      "--secondary": "#ebdbb2",
      "--secondary-foreground": "#3c3836",
      "--muted": "#ebdbb2",
      "--muted-foreground": "#7c6f64",
      "--accent": "#ebdbb2",
      "--accent-foreground": "#3c3836",
      "--destructive": "#cc241d",
      "--destructive-foreground": "#cc241d",
      "--border": "#d5c4a1",
      "--input": "#d5c4a1",
      "--ring": "#458588",
      "--info": "#458588",
      "--info-foreground": "#458588",
      "--success": "#98971a",
      "--success-foreground": "#98971a",
      "--warning": "#d79921",
      "--warning-foreground": "#d79921",
    },
  },
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    group: "gruvbox",
    base: "dark",
    variables: {
      "--background": "#282828",
      "--foreground": "#ebdbb2",
      "--card": "#1d2021",
      "--card-foreground": "#ebdbb2",
      "--popover": "#1d2021",
      "--popover-foreground": "#ebdbb2",
      "--primary": "#83a598",
      "--primary-foreground": "#282828",
      "--secondary": "#3c3836",
      "--secondary-foreground": "#ebdbb2",
      "--muted": "#3c3836",
      "--muted-foreground": "#a89984",
      "--accent": "#3c3836",
      "--accent-foreground": "#ebdbb2",
      "--destructive": "#fb4934",
      "--destructive-foreground": "#fb4934",
      "--border": "#504945",
      "--input": "#504945",
      "--ring": "#83a598",
      "--info": "#83a598",
      "--info-foreground": "#83a598",
      "--success": "#b8bb26",
      "--success-foreground": "#b8bb26",
      "--warning": "#fabd2f",
      "--warning-foreground": "#fabd2f",
    },
  },
];
