import type { ThemeDefinition } from "../types";

export const NEBULA_THEMES: readonly ThemeDefinition[] = [
  {
    id: "nebula-light",
    label: "Nebula Light",
    group: "nebula",
    base: "light",
    variables: {
      "--background": "#e3e3d3",
      "--foreground": "#212535",
      "--card": "#f4f4e6",
      "--card-foreground": "#212535",
      "--popover": "#ffffff",
      "--popover-foreground": "#212535",
      "--primary": "#6378fd",
      "--primary-foreground": "#ffffff",
      "--secondary": "#f4f4e6",
      "--secondary-foreground": "#212535",
      "--muted": "#f4f4e6",
      "--muted-foreground": "#666c85",
      "--accent": "#e3e3d3",
      "--accent-foreground": "#212535",
      "--destructive": "#f04050",
      "--destructive-foreground": "#f04050",
      "--border": "#b1b1ac",
      "--input": "#b1b1ac",
      "--ring": "#6378fd",
      "--info": "#5cceff",
      "--info-foreground": "#5cceff",
      "--success": "#54d993",
      "--success-foreground": "#54d993",
      "--warning": "#e78e00",
      "--warning-foreground": "#e78e00",
    },
  },
  {
    id: "nebula-dark",
    label: "Nebula Dark",
    group: "nebula",
    base: "dark",
    variables: {
      "--background": "#151821",
      "--foreground": "#f4f4e6",
      "--card": "#2a2e3c",
      "--card-foreground": "#f4f4e6",
      "--popover": "#212535",
      "--popover-foreground": "#f4f4e6",
      "--primary": "#6378fd",
      "--primary-foreground": "#f4f4e6",
      "--secondary": "#212535",
      "--secondary-foreground": "#f4f4e6",
      "--muted": "#2a2e3c",
      "--muted-foreground": "#b1b1ac",
      "--accent": "#212535",
      "--accent-foreground": "#f4f4e6",
      "--destructive": "#f04050",
      "--destructive-foreground": "#f04050",
      "--border": "#4e5159",
      "--input": "#4e5159",
      "--ring": "#6378fd",
      "--info": "#5cceff",
      "--info-foreground": "#5cceff",
      "--success": "#54d993",
      "--success-foreground": "#54d993",
      "--warning": "#ffc60a",
      "--warning-foreground": "#ffc60a",
    },
  },
];
