import type { ThemeDefinition } from "../types";

export const ROSE_PINE_THEMES: readonly ThemeDefinition[] = [
  {
    id: "rose-pine",
    label: "Ros\u00e9 Pine",
    group: "rose-pine",
    base: "dark",
    variables: {
      "--background": "#191724",
      "--foreground": "#e0def4",
      "--card": "#1f1d2e",
      "--card-foreground": "#e0def4",
      "--popover": "#26233a",
      "--popover-foreground": "#e0def4",
      "--primary": "#c4a7e7",
      "--primary-foreground": "#191724",
      "--secondary": "#26233a",
      "--secondary-foreground": "#e0def4",
      "--muted": "#26233a",
      "--muted-foreground": "#6e6a86",
      "--accent": "#26233a",
      "--accent-foreground": "#e0def4",
      "--destructive": "#eb6f92",
      "--destructive-foreground": "#eb6f92",
      "--border": "#393552",
      "--input": "#393552",
      "--ring": "#c4a7e7",
      "--info": "#9ccfd8",
      "--info-foreground": "#9ccfd8",
      "--success": "#31748f",
      "--success-foreground": "#31748f",
      "--warning": "#f6c177",
      "--warning-foreground": "#f6c177",
    },
  },
  {
    id: "rose-pine-moon",
    label: "Ros\u00e9 Pine Moon",
    group: "rose-pine",
    base: "dark",
    variables: {
      "--background": "#232136",
      "--foreground": "#e0def4",
      "--card": "#2a273f",
      "--card-foreground": "#e0def4",
      "--popover": "#393552",
      "--popover-foreground": "#e0def4",
      "--primary": "#c4a7e7",
      "--primary-foreground": "#232136",
      "--secondary": "#393552",
      "--secondary-foreground": "#e0def4",
      "--muted": "#393552",
      "--muted-foreground": "#6e6a86",
      "--accent": "#393552",
      "--accent-foreground": "#e0def4",
      "--destructive": "#eb6f92",
      "--destructive-foreground": "#eb6f92",
      "--border": "#44415a",
      "--input": "#44415a",
      "--ring": "#c4a7e7",
      "--info": "#9ccfd8",
      "--info-foreground": "#9ccfd8",
      "--success": "#3e8fb0",
      "--success-foreground": "#3e8fb0",
      "--warning": "#f6c177",
      "--warning-foreground": "#f6c177",
    },
  },
  {
    id: "rose-pine-dawn",
    label: "Ros\u00e9 Pine Dawn",
    group: "rose-pine",
    base: "light",
    variables: {
      "--background": "#faf4ed",
      "--foreground": "#575279",
      "--card": "#fffaf3",
      "--card-foreground": "#575279",
      "--popover": "#f2e9e1",
      "--popover-foreground": "#575279",
      "--primary": "#907aa9",
      "--primary-foreground": "#faf4ed",
      "--secondary": "#f2e9e1",
      "--secondary-foreground": "#575279",
      "--muted": "#f2e9e1",
      "--muted-foreground": "#9893a5",
      "--accent": "#f2e9e1",
      "--accent-foreground": "#575279",
      "--destructive": "#b4637a",
      "--destructive-foreground": "#b4637a",
      "--border": "#dfdad9",
      "--input": "#dfdad9",
      "--ring": "#907aa9",
      "--info": "#56949f",
      "--info-foreground": "#56949f",
      "--success": "#286983",
      "--success-foreground": "#286983",
      "--warning": "#ea9d34",
      "--warning-foreground": "#ea9d34",
    },
  },
];
