import type { ThemeDefinition } from "../types";

export const TOKYO_NIGHT_THEMES: readonly ThemeDefinition[] = [
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    group: "tokyo-night",
    base: "dark",
    variables: {
      "--background": "#1a1b26",
      "--foreground": "#a9b1d6",
      "--card": "#16161e",
      "--card-foreground": "#a9b1d6",
      "--popover": "#16161e",
      "--popover-foreground": "#a9b1d6",
      "--primary": "#7aa2f7",
      "--primary-foreground": "#1a1b26",
      "--secondary": "#292e42",
      "--secondary-foreground": "#a9b1d6",
      "--muted": "#292e42",
      "--muted-foreground": "#565f89",
      "--accent": "#292e42",
      "--accent-foreground": "#a9b1d6",
      "--destructive": "#f7768e",
      "--destructive-foreground": "#f7768e",
      "--border": "#3b4261",
      "--input": "#3b4261",
      "--ring": "#7aa2f7",
      "--info": "#7aa2f7",
      "--info-foreground": "#7aa2f7",
      "--success": "#9ece6a",
      "--success-foreground": "#9ece6a",
      "--warning": "#e0af68",
      "--warning-foreground": "#e0af68",
    },
  },
  {
    id: "tokyo-night-storm",
    label: "Tokyo Night Storm",
    group: "tokyo-night",
    base: "dark",
    variables: {
      "--background": "#24283b",
      "--foreground": "#a9b1d6",
      "--card": "#1f2335",
      "--card-foreground": "#a9b1d6",
      "--popover": "#1f2335",
      "--popover-foreground": "#a9b1d6",
      "--primary": "#7aa2f7",
      "--primary-foreground": "#24283b",
      "--secondary": "#3b4261",
      "--secondary-foreground": "#a9b1d6",
      "--muted": "#3b4261",
      "--muted-foreground": "#565f89",
      "--accent": "#3b4261",
      "--accent-foreground": "#a9b1d6",
      "--destructive": "#f7768e",
      "--destructive-foreground": "#f7768e",
      "--border": "#3b4261",
      "--input": "#3b4261",
      "--ring": "#7aa2f7",
      "--info": "#7aa2f7",
      "--info-foreground": "#7aa2f7",
      "--success": "#9ece6a",
      "--success-foreground": "#9ece6a",
      "--warning": "#e0af68",
      "--warning-foreground": "#e0af68",
    },
  },
  {
    id: "tokyo-night-light",
    label: "Tokyo Night Light",
    group: "tokyo-night",
    base: "light",
    variables: {
      "--background": "#d5d6db",
      "--foreground": "#343b58",
      "--card": "#cbccd1",
      "--card-foreground": "#343b58",
      "--popover": "#cbccd1",
      "--popover-foreground": "#343b58",
      "--primary": "#34548a",
      "--primary-foreground": "#d5d6db",
      "--secondary": "#c4c5ca",
      "--secondary-foreground": "#343b58",
      "--muted": "#c4c5ca",
      "--muted-foreground": "#6a6e7e",
      "--accent": "#c4c5ca",
      "--accent-foreground": "#343b58",
      "--destructive": "#8c4351",
      "--destructive-foreground": "#8c4351",
      "--border": "#b4b5b9",
      "--input": "#b4b5b9",
      "--ring": "#34548a",
      "--info": "#34548a",
      "--info-foreground": "#34548a",
      "--success": "#33635c",
      "--success-foreground": "#33635c",
      "--warning": "#8f5e15",
      "--warning-foreground": "#8f5e15",
    },
  },
];
